scriptencoding utf-8
set encoding=utf-8
set runtimepath^=~/.vim runtimepath+=~/.vim/after
set foldopen+=jump
" let &packpath=&runtimepath

"turn on syntax highlighting
syntax on

" Change leader to a comma because the backslash is too far away
" That means all \x commands turn into ,x
" The mapleader has to be set before vundle starts loading all
" the plugins.
let mapleader=","

" Easy Motion default
map <Leader> <Plug>(easymotion-prefix)

colo desert

" Plugin management
call plug#begin()
Plug 'christoomey/vim-tmux-navigator'
Plug 'vim-scripts/YankRing.vim'
Plug 'python-mode/python-mode', { 'branch': 'develop' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --no-key-bindings --no-update-rc --completion' }
Plug 'easymotion/vim-easymotion'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'lervag/vimtex'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'rhysd/vim-grammarous'
Plug 'dpelle/vim-LanguageTool'
Plug 'ron89/thesaurus_query.vim'

" Don't load cause Minerva's Vim is super old
if (hostname() == 'Fedora.Y70')
    Plug 'Valloric/YouCompleteMe'
endif
call plug#end()


" Tmux Navigation
" Don't allow any default key-mappings.
let g:tmux_navigator_no_mappings = 1

" Re-enable tmux_navigator.vim default bindings, minus <c-\>.
" <c-\> conflicts with NERDTree "current file".

nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>

" SETtings
set ttimeout
set timeoutlen=1000
set ttimeoutlen=0
set background=dark
set foldmethod=indent
set foldlevelstart=0
set tabstop=2
set softtabstop=0
set shiftwidth=4
set expandtab
set smarttab
set nowrap
set number
set listchars=tab:>>,trail:~,extends:>,precedes:<
set list
set incsearch
set nohlsearch
set relativenumber

"---------- FUNCTIONS -----------"
" Function for trimming whitespace
fun! TrimWhiteSpace()
  let l:save = winsaveview()
  %s/\s\+$//e
  call winrestview(l:save)
endfun

" Custom
map <silent> <F12> :call TrimWhiteSpace()<cr>
cmap w!! w !sudo tee > /dev/null %

" Function for switch a buffer to a existing tab
function MoveToPrevTab()
    " There is only one window
    if tabpagenr('$') == 1 && winnr('$') == 1
        return
    endif
    " Prepare a new window
    let l:tab_nr = tabpagenr('$')
    let l:cur_buf = bufnr('%')
    if tabpagenr() != 1
        close!
        if l:tab_nr == tabpagenr('$')
            tabprev
        endif
        sp
    else
        close!
        exe "0tabnew"
    endif
    " Opening current buffer in new window
    exe "b" .l:cur_buf
endfunc

function MoveToNextTab()
    " There is only one window
    if tabpagenr('$') == 1 && winnr('$') == 1
        return
    endif
    " Prepare new window
    let l:tab_nr = tabpagenr('$')
    let l:cur_buf = bufnr('%')
    if tabpagenr() < tab_nr
        close!
        if l:tab_nr == tabpagenr('$')
            tabnext
        endif
        sp
    else
        close!
        tabnew
    endif
    " Opening current buffer in new window
    exe "b" .l:cur_buf
endfunc

" Custom Mappings keys
nnoremap <A-.> :call MoveToNextTab()<CR>
nnoremap <A-,> :call MoveToPrevTab()<CR>
nnoremap H gT
nnoremap L gt
nnoremap K :YcmCompleter GetDoc<CR>
nnoremap ff :setlocal foldlevel=1<CR>

"" Python Plugin Settings
if (hostname() == 'Fedora.Y70')
    let g:pymode_python='python3'
endif
let g:pymode_options_max_line_length=120
let g:pymode_lint_options_pep8 =
    \ {'max_line_length': g:pymode_options_max_line_length}
let g:pymode_doc_bind='B'
let g:pymode_rope=0

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
" let g:UltiSnipsListSnippets = '<c-g>'
" let g:UltiSnipsExpandTrigger = '<tab>'
" let g:UltiSnipsJumpForwardTrigger = '<tab>'
" let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

" CtrlP file finding
let g:ctrlp_custom_ignore = '\v[\/](build|__pycache__|git|htmlcov)|(\.(swp|git))$'
let g:ctrlp_map = '<c-u>'
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<2-LeftMouse>'],
    \ 'AcceptSelection("t")': ['<cr>'],
    \ }

" LanguageTool Jar
let g:languagetool_jar='$HOME/.vim/LanguageTool-4.5/languagetool-commandline.jar'

" Filetypes
au BufNewFile,BufRead *.tsv		setf tsv

" PUDB settings
if has('nvim')
 " let g:python_host_prog='~/.virtualenvs/neovim2/bin/python'
 " let g:python3_host_prog='~/.virtualenvs/neovim3/bin/python'
  " Set python versions
  "
  let g:python_host_prog="~/anaconda3/envs/lodi2/bin/python2"
  let g:python3_host_prog="~/anaconda3/envs/mmeds-stable/bin/python3"
  " set the virtual env python used to launch the debugger
  let g:pudb_python='~/.virtualenvs/poweruser_tools/bin/python'
  " set the entry point (script) to use for pudb
  let g:pudb_entry_point='~/src/poweruser_tools/test/test_templates.py'
  " Unicode symbols work fine (nvim, iterm, tmux, nyovim tested)
  let g:pudb_breakpoint_symbol='☠'
endif
