# Setup prezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source "${HOME}/.sel/zsh/antigen.zsh"

# Modules
antigen use prezto
antigen apply

# Custom alias's
alias userpath='sudo env "PATH=$PATH"'
alias smiwatch='watch -n 0.5 nvidia-smi'
alias l='ls -lah'
alias dir='ls -Alh | less'
alias clean='rm -f *~ .*~ \#*\#'
alias mv='mv -i'
alias ku='pkill -u dawallach'
alias rmr='rm -rf'
alias cpr='cp -rf'
alias wemacs='env TERM=xterm-256color emacs -nw'
alias srcocc='source /usr/local/bin/kroc-setup.sh'
alias ssv='ssh dawallach@mote.cs.vassar.edu'
alias swap='xmodmap ~/Documents/.xmodmap'
alias ssm='ssh wallad07@login2.hpc.mssm.edu'
alias ssx='ssh -XY wallad07@login2.hpc.mssm.edu'
alias ssc='ssh -XY wallad07@chimera.hpc.mssm.edu'
alias check='grep "egg" -R *; grep "pyc" -R *'
alias cleane='rm -rf build; rm -rf dist; rm -rf ensemble.egg-info; rm ensemble/*.pyc;'
alias tach='tmux attach-session -t 0'
alias pperf='sudo cpupower frequency-set -g performance'
alias psave='sudo cpupower frequency-set -g ondemand'
alias oct='octave --no-gui'
alias susegrub='grub2-mkconfig -o /boot/grub2/grub.cfg'
alias ta='task add tag:work project:mmeds'
alias tw='task tag:work'

# Directory Navigation
alias ds='dirs -v'

# Python
alias py='python'
alias pin='python setup.py install&>/dev/null'
alias sac='conda activate'
alias sad='conda deactivate'
alias jb='jupyter notebook'
alias pt='pytest --cov=./ -W ignore::DeprecationWarning -W ignore::FutureWarning -s --durations=0'

# Git
alias gitcleanup='git fetch -p && git branch -vv | awk '\''/: gone]/{print $1}'\'' | xargs git branch -d'
alias gcmp='ga; gc -m "Update"; gp'
alias gpush='cd ~/.sel; gcmp; po;'
alias gpull='cd ~/.sel; git pull; po;'
alias g='git'
alias ga='git add .'
alias gc='git commit'
alias gp='git push'
alias gst='git status'


# Makes git auto completion faster favouring for local completions
__git_files () {
    _wanted files expl 'local files' _files
}

# R Nonsense
alias setupR='export PKG_CXXFLAGS=`Rscript -e '\''Rcpp:::CxxFlags()'\''`; export PKG_LIBS=`Rscript -e '\''-enable-shared-lib -ligraph'\''`'

# Port Access
alias allow='sudo setcap '\''cap_net_bind_service=+ep'\'
alias gpg='gpg2'

# Show human friendly numbers and colors
alias df='df -h'
alias du='du -h -d 2'

# Kill processes
alias ka9='killall -9'
alias k9='kill -9'

# Options
setopt rmstarsilent
KEYTIMEOUT=10

# Key Bindings
bindkey -v

# Search history for commands
bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward

# FZF search
ctrlp() {
    zle reset-prompt
    print -z - $BUFFER $( find . -not -path '*/\.*' -nowarn 2>&1 | sed '/Permission denied/d;' | fzf --height 10)
    zle send-break
}

zle -N ctrlp
bindkey "^U" ctrlp

# Environment Variables
export LC_CTYPE=en_US.UTF-8
export FZF_COMPLETION_TRIGGER='~~'
export name='.sel'
export SEL="${HOME}/${name}"
export PATH="${HOME}/${name}/scripts:$PATH"


# Custom params for different locations
if [[ $(hostname) == "Fedora.Y70" ]]; then
    xset r rate 250 45
    # Vim
    alias vi='vim'
    alias vlog="vi '+normal GA' $HOME/mmeds_server_data/mmeds_log.txt"
    alias mysql="mysql -u root -c mmeds_data1"
    module use ~/.modules/modulefiles
    export CONDA_DIR=/home/david/anaconda3/
elif [[ $(hostname) == 'node2-3' ]]; then
    module load Firefox
    module use /hpc/packages/minerva-common/modulefiles
    module load tmux
    module load anaconda

    prompt skwp


    export MMEDS="/sc/orga/projects/MMEDS"
    export PATH="$HOME/.local/bin:$PATH"
    export TMPDIR="/local/tmp"
    export CONDA_DIR='/hpc/packages/minerva-common/anaconda2/'

    # Minerva Aliases
    alias towork='cd /sc/orga/projects/clemej05a/wallach'
    alias remlinks='find -L . -name . -o -type d -prune -o -type l -exec rm {} +'
    alias logindb='mysql -h db1 -u wallad07_db1 -p wallad07_db1'
    alias srcens='source /sc/orga/projects/clemej05a/wallach/ENS/python_env/bin/activate'
    alias duh='du -sh'
    alias mmedsadmin='/opt/collab/bin/cologin mmedsadmin'
    alias tommeds="cd $MMEDS"
    alias vi='vim'
    alias vlog="vi '+normal GA' $MMEDS/mmeds_server_data/mmeds_log.txt"
    # source /hpc/packages/minerva-common/anaconda2/4.3.0/etc/profile.d/conda.sh  # commented out by conda initialize

fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup=$("${CONDA_DIR}/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "{$CONDA_DIR}/etc/profile.d/conda.sh" ]; then
        echo 'if'
       . "${CONDA_DIR}/etc/profile.d/conda.sh"  # commented out by conda initialize
    else
        export PATH="${CONDA_DIR}/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
